/** Hero frame sequence manifest — files generated by `pnpm gen:hero`. */
export const FRAME_COUNT = 72;

export const frameSrc = (i: number) =>
  `/hero/frames/frame-${String(i).padStart(3, "0")}.webp`;
